version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile_1
    ports:
      - "5000:5000"
    environment:
      - ZONE_ID=88212a53b6feba598b197f3508f35b52
      - CF_API_KEY=ab590d1c5d3139416fef3d173ad4267a75a41
      - CF_API_EMAIL=safe@hostspaceng.com
    volumes:
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VUE_APP_PROXY_URL=http://35.178.115.47:5000/
